= Test Helpers

*Assertion library for Ethereum smart contract testing.* Make sure your contracts behave as expected!

 * Check that xref:api.adoc#expect-revert[transactions revert] for the correct reason
 * Verify xref:api.adoc#expect-event[events] where emitted with the right values
 * Track xref:api.adoc#balance[balance changes] elegantly
 * Handle xref:api.adoc#bn[very large numbers]
 * Simulate the xref:api.adoc#time[passing of time]

Test Helpers integrates seamlessly with xref:test-environment::index.adoc[*OpenZeppelin Test Environment*], but it also supports both Truffle tests and regular web3 workflows.

== Overview

=== Installation

```bash
npm install --save-dev @openzeppelin/test-helpers
```

==== Hardhat (formerly Buidler)

Install `web3` and the `hardhat-web3` plugin.

```bash
npm install --save-dev @nomiclabs/hardhat-web3 web3
```

Remember to include the plugin in your configuration as explained in the https://hardhat.org/plugins/nomiclabs-hardhat-web3.html#installation[installation instructions].

=== Usage

Import `@openzeppelin/test-helpers` in your test files to access the different assertions and utilities.

NOTE: The following snippet uses xref:test-environment::index.adoc[OpenZeppelin Test Environment]: a Truffle-based setup would work the same way.

```javascript
const { accounts, contract } = require('@openzeppelin/test-environment');

const {
  BN,           // Big Number support
  constants,    // Common constants, like the zero address and largest integers
  expectEvent,  // Assertions for emitted events
  expectRevert, // Assertions for transactions that should fail
} = require('@openzeppelin/test-helpers');

const ERC20 = contract.fromArtifacts('ERC20');

describe('ERC20', function () {
  const [sender, receiver] =  accounts;

  beforeEach(async function () {
    // The bundled BN library is the same one web3 uses under the hood
    this.value = new BN(1);

    this.erc20 = await ERC20.new();
  });

  it('reverts when transferring tokens to the zero address', async function () {
    // Conditions that trigger a require statement can be precisely tested
    await expectRevert(
      this.erc20.transfer(constants.ZERO_ADDRESS, this.value, { from: sender }),
      'ERC20: transfer to the zero address',
    );
  });

  it('emits a Transfer event on successful transfers', async function () {
    const receipt = await this.erc20.transfer(
      receiver, this.value, { from: sender }
    );

    // Event assertions can verify that the arguments are the expected ones
    expectEvent(receipt, 'Transfer', {
      from: sender,
      to: receiver,
      value: this.value,
    });
  });

  it('updates balances on successful transfers', async function () {
    this.erc20.transfer(receiver, this.value, { from: sender });

    // BN assertions are automatically available via chai-bn (if using Chai)
    expect(await this.erc20.balanceOf(receiver))
      .to.be.bignumber.equal(this.value);
  });
});
```

== Learn More

* Head to xref:configuration.adoc[Configuration] for advanced settings.
* For detailed usage information, take a look at the xref:api.adoc[API Reference].
